name: flowstorage_fsc
description: Flowstorage App.
publish_to: 'none'

version: 2.1.4

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  mysql_client: ^0.0.27
  encrypt: ^5.0.0
  file_picker: ^5.2.4 
  gallery_saver: ^2.3.2
  path_provider: ^2.0.12
  intl: ^0.18.0
  image_gallery_saver: ^2.0.1
  webview_flutter: ^4.0.7
  clipboard: ^0.1.3
  syncfusion_flutter_pdfviewer: ^20.3.56
  syncfusion_flutter_charts: ^20.3.50
  google_fonts: ^4.0.3
  just_audio: ^0.9.32 
  video_player: ^2.6.1
  flutter_native_image: ^0.0.6+1
  flutter_local_notifications: ^14.0.0+1
  cunning_document_scanner: ^1.1.1
  pdf: ^3.10.4  
  flutter_secure_storage: ^7.0.0
  flutter_cache_manager: ^3.1.2
  logger: ^1.4.0
  flutter_staggered_grid_view: ^0.4.0
  open_file: ^3.3.2  
  fluttertoast: ^8.2.2
  video_thumbnail: ^0.5.3
  image_picker_plus: ^0.5.9
  provider: ^6.0.5
  get_it: ^7.6.0
  quick_actions: ^1.0.6
  share_plus: ^7.0.0
  archive: ^3.4.3
  flutter_sharing_intent: ^1.1.0
  app_settings: ^5.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
